version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/server # Set the working directory to /app/server
    environment:
      NODEMAILER_EMAIL: $NODEMAILER_EMAIL
      NODEMAILER_PASS: $NODEMAILER_PASS
      DB_DATABASE: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      SESSION_SECRET: $SESSION_SECRET
      PORT: $PORT
      ENV: $ENV
    ports:
      - "5000:80" # Expose the correct port
