version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/server # Set the working directory to /app/server
    environment:
      NODEMAILER_EMAIL: $NODEMAILER_EMAIL
      NODEMAILER_PASS: $NODEMAILER_PASS
      DB_DATABASE: $DB_DATABASE
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      SESSION_SECRET: $SESSION_SECRET
      PORT: $PORT
      ENV: $ENV
  nginx:
    container_name: nginx
    restart: always
    image: jonasal/nginx-certbot
    ports:
      - 80:80
    volumes:
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - app
