name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName ${{ secrets.SSH_IP }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END

      - name: Set environment variables
        run: |
          ssh my-vps "cd /var/www/messenger-app && export NODEMAILER_EMAIL=${{ secrets.NODEMAILER_EMAIL }} \
          NODEMAILER_PASS=${{ secrets.NODEMAILER_PASS }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_HOST=${{ secrets.DB_HOST }} \
          DB_PORT=${{ secrets.DB_PORT }} \
          SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
          PORT=${{ secrets.PORT }}"

      - name: Deploy site
        run: ssh my-vps '/var/www/redeploy.sh'
