name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName ${{ secrets.SSH_IP }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END

      - name: Start Docker Daemon
        run: ssh my-vps "sudo systemctl start docker"

      - name: Remove existing files
        run: ssh my-vps "rm -rf /var/www/*"

      - name: Clone repository
        run: |
          ssh my-vps "rm -rf /tmp/messenger-app && git clone https://github.com/khalil0525/Messenger-app.git /tmp/messenger-app"
          ssh my-vps "mv /tmp/messenger-app/* /var/www"

      - name: Start Docker
        run: ssh my-vps "cd /var/www && sudo docker-compose up -d"
