name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName ${{ secrets.SSH_IP }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END

      - name: Start Docker Daemon
        run: ssh my-vps "sudo systemctl start docker"

      - name: Remove existing files
        run: ssh my-vps "rm -rf /var/www/*"

      - name: Stop and Remove Existing Docker Container
        run: |
          ssh my-vps "cd /var/www && sudo docker-compose down"

      - name: Clone repository
        run: |
          ssh my-vps "if [ ! -d /var/www/messenger-app ]; then git clone https://github.com/khalil0525/Messenger-app.git /var/www/messenger-app; fi"
          ssh my-vps "mv /var/www/messenger-app/* /var/www"

      - name: Start Docker
        run: |
          ssh my-vps "cd /var/www/messenger-app && export NODEMAILER_EMAIL=${{ secrets.NODEMAILER_EMAIL }} \
          NODEMAILER_PASS=${{ secrets.NODEMAILER_PASS }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_HOST=${{ secrets.DB_HOST }} \
          DB_PORT=${{ secrets.DB_PORT }} \
          SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
          PORT=${{ secrets.PORT }}"

      - name: Deploy site
        run: ssh my-vps '/var/www/redeploy-site.sh'
