name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        working-directory: ./client
        run: npm install

      - name: Build React App
        working-directory: ./client
        run: npm run build

      - name: Commit Build to Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Add built React app"
          git push
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      REACT_APP_API_URL: http://ec2-54-224-72-128.compute-1.amazonaws.com
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName ${{ secrets.SSH_IP }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END

      - name: Deploy site
        run: ssh my-vps 'cd /var/www/ && ./redeploy.sh'
